export interface Student{
    Name:{
        FirstName:string,
        MiddleName:string,
        LastName:string
    },
    BirthDetail:{
        DOB:Date,
        PlaceOfBirth:string
    }
    PlaceOfBirth:string,
    Languages:{
        FirstLanguage:string,
        SecondLanguage:string
    },
    Address:{
        City:string,
        State:string,
        Country:string,
        PIN:number
    },
    Father:{
        FullName:{
            FirstName:string,
            MiddleName:string,
            LastName:string
        },
        Email:string,
        EducationQualification:string,
        Profession:string,
        Designation:string,
        Phone:number
    },
    Mother:{
        FullName:{
            FirstName:string,
            MiddleName:string,
            LastName:string
        },
        Email:string,
        EducationQualification:string,
        Profession:string,
        Designation:string,
        Phone:number
    }
}